---
- name: start Matrix
  community.kubernetes.k8s:
    definition:
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: '{{ ansible_operator_meta.name }}-matrix'
        namespace: '{{ ansible_operator_meta.namespace }}'
      spec:
        replicas: "{{size}}"
        selector:
          matchLabels:
            app: matrix
        template:
          metadata:
            labels:
              app: matrix
          spec:
            containers:
            - name: matrix
              command:
              - python
              - matrix.py
              image: "guylurieg/matrix:latest"
              ports:
                - containerPort: 80

# tasks file for Matrix
